# Generated by Django 5.1.5 on 2025-02-06 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='QuizTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=60)),
                ('max_score', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramTaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.file')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramTaskTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=1000)),
                ('output', models.CharField(max_length=1000)),
                ('program_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testings.programtask')),
            ],
        ),
        migrations.CreateModel(
            name='QuizTaskChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('quiz_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testings.quiztask')),
            ],
        ),
        migrations.CreateModel(
            name='QuizTaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testings.quiztaskchoice')),
            ],
        ),
        migrations.AddField(
            model_name='quiztask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testings.task'),
        ),
        migrations.AddField(
            model_name='programtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testings.task'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='started', max_length=20)),
                ('score', models.FloatField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('score', models.FloatField(default=0)),
                ('program_task_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testings.programtaskresult')),
                ('quiz_task_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testings.quiztaskresult')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testings.task')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testings.testresult')),
            ],
        ),
        migrations.CreateModel(
            name='TestVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.FloatField(default=1)),
                ('config_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.file')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testings.test')),
            ],
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testings.testversion'),
        ),
        migrations.AddField(
            model_name='task',
            name='test_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testings.testversion'),
        ),
    ]
