# Generated by Django 5.1.5 on 2025-02-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskresult',
            name='created_at',
        ),
    ]
