# Generated by Django 5.1.5 on 2025-02-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testings', '0002_remove_taskresult_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
