# Generated by Django 5.1.5 on 2025-02-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testings', '0003_alter_testresult_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testversion',
            name='max_score',
            field=models.FloatField(default=1),
        ),
    ]
