# Generated by Django 5.1.5 on 2025-02-06 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('testings', '0004_testversion_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testversion',
            name='config_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.file'),
        ),
    ]
