# Generated by Django 5.1.5 on 2025-02-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testings', '0006_programtaskresult_taskresult_program_task_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztaskresult',
            name='quiz_task',
        ),
    ]
