# Generated by Django 5.1.5 on 2025-02-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testings', '0007_remove_quiztaskresult_quiz_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiztaskresult',
            old_name='selected_choice',
            new_name='choice',
        ),
    ]
